forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class RegistrationForm(FlaskForm):
	username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
	email = StringField('Email', validators=[DataRequired(), Email()])
	password = PasswordField('Password', validators=[DataRequired()])
	confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])

	submit = SubmitField("Sign Up")

class LoginForm(FlaskForm):
	username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
	password = PasswordField('Password', validators=[DataRequired()])

	remember = BooleanField("Remember Me")

	submit = SubmitField("Login")

auth.py
from flask import render_template, url_for, flash, redirect, Blueprint
from forms import RegistrationForm, LoginForm
from views import views_blueprint


auth_blueprint = Blueprint('auth', __name__)

# Register User Page
@auth_blueprint.route("/reguse", methods=["GET", "POST"])
def registerUser():
    form = RegistrationForm()
    if form.validate_on_submit():
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('views.home'))
    return render_template('register.html', title='Register', form=form)

# Login Page
@auth_blueprint.route("/login", methods=["GET", "POST"])
def loginUser():
    form = LoginForm()
    return render_template('login.html', title='Login', form=form)

main.py
from flask import Flask
from views import views_blueprint
from auth import auth_blueprint


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'XXXXXXXXXXXXXXXXXXXXXXXXX'

    # Register Blueprint
    app.register_blueprint(views_blueprint, url_prefix='/')
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app = create_app()

if __name__ == '__main__':
    app.run(debug=True)

views.py
from flask import render_template, url_for, Blueprint


views_blueprint = Blueprint('views', __name__)

# Home is supposed to return after login
@views_blueprint.route("/")
def home():
    return render_template('home.html')

# Contact Page
@views_blueprint.route("/contact")
def contactPage():
    return render_template('contact.html')

# About Page
@views_blueprint.route("/about")
def aboutPage():
    return render_template('about.html')

# Donation Page
@views_blueprint.route("/donate")
def donatePage():
    return render_template('donate.html')

templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
    <img src="{{ url_for('static', filename='ThePath\'sMission.jpg') }}" width="100%" height="100%">
    <h2>Our History</h2>
        <div class="row">
            <div class="col-md-4">
                <img src="{{ url_for('static', filename='PATH-Main-Right.jpg') }}" width="60%" height="60%">
                <p>This is Our Office, Come Visit!</p>
            </div>
            <div class="col-md-4">
                <img src="{{ url_for('static', filename='NewsPaper-Cutting4.jpg') }}" width="60%" height="60%">
                <p>September 28, 1983; City of Farmington OK's shelter to be built.</p>
            </div>
            <div class="col-md-4">
                <img src="{{ url_for('static', filename='OldPATH1.jpg') }}" width="60%" height="60%">
                <p>PATH Had very humble beginnings, with not much room.</p>
            </div>
            <div class="col-md-4">
                <img src="{{ url_for('static', filename='OldPATH2.jpg') }}" width="60%" height="60%">
                <p>This is one of the first images of PATH in its humble beginning.</p>
            </div>
            <div class="col-md-4">
                <img src="{{ url_for('static', filename='OldPATH3.jpg') }}" width="60%" height="60%">
                <p>PATH has a long history with feeding and leading the homeless to better opportunity.</p>
            </div>
            <div class="col-md-4">
                <img src="{{ url_for('static', filename='OldPATH4.jpg') }}" width="60%" height="60%">
                <p>PATH has continued to impact those in need.</p>
            </div>
            <div class="col-md-4">
                <img src="{{ url_for('static', filename='FeedingHomeless2.jpg') }}" width="60%" height="60%">
                <p></p>
            </div>
        </div>
    <p>If you have any questions or feedback, please don't hesitate to <a href="{{ url_for('views.contactPage') }}">Contact Us.</a>.</p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrit="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>PATH - People Assisting The Homeless - {{ title }}</title>
    {% else %}
        <title>PATH - People Assisting The Homeless</title>
    {% endif %}

</head>
<body>
    <header class="site-header">
      <a href="{{ url_for('views.home') }}">
        <img src="{{ url_for('static', filename='PATH-Main.png') }}" width="75%" height="75%" alt="PATH Logo">
      </a>
      <h1>PATH - People Assisting The Homeless</h1>
        <nav class="navbar navbar-expand-sm navbar-light bg-steel fixed-top">
          <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            	<span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('views.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('views.aboutPage') }}">About</a>
                <a class="nav-item nav-link" href="{{ url_for('views.contactPage') }}">Contact</a>
                <a class="nav-item nav-link" href="{{ url_for('views.donatePage') }}">Donate</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ url_for('auth.loginUser') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('auth.registerUser') }}">Register</a>
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li><a href="{{ url_for('views.aboutPage') }}">About Us</a></li>
                <li><a href="{{ url_for('views.contactPage') }}">Contact Us</a></li>
                <li><a href="{{ url_for('views.donatePage') }}">Donate Today!</a></li>
                <li><a href="https://facebook.com/PATHNM/">Keep Up To Date With Us!</a></li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% block title %}PATH{% endblock %}
{% block content %}
    <h1>Our Company</h1>

    <h2>About Us</h2>
    <p>Welcome to PATH! We are a group of passionate and caring individuals with a mission: Our mission is To temporarily provide for the basic needs of homeless persons; to provide information, guidance, and support services empowering those we assist to regain productive, self-supportive lifestyles. To provide a hot, nutritious meal for those in need free of charge.</p>

    <h2>Our Services</h2>
    <ul>
        <li>Information & Job Search Guidance</li>
        <li>Residential Savings Plans</li>
        <li>PATH To Recovery</li>
        <li>Housing For Those In Need</li>
    </ul>

    <h2>Contact Us</h2>
    <p>If you have any questions or would like to learn more about our services, please don't hesitate to contact us:</p>
    <ul>
        <li>Phone: 555-1234</li>
        <li>Email: info@ourcompany.com</li>
        <li>Address: 123 Main Street, Anytown USA</li>
    </ul>
{% endblock %}

templates/donate.html
{% extends 'base.html' %}
{% block content %}
  <header>
    <h1>Donate</h1>
  </header>
  <main>
    <section>
      <p>Your donation will help us to continue our goal to help people experiencing homelessness </p>
      <p>get off the streets and recover for a chance at a better future.</p>
      <p>We accept donations of any amount, and all donations are tax-deductible.</p>
      <p>We track donation reciepts for 6 months. To donate, please click the button below.</p>
      <a href="https://www.paypal.com/donate/?hosted_button_id=XXXXXXXXXXXXX" class="button">Donate</a>
    </section>
    <section>
      <p>Thank you for your support!</p>
    </section>
  </main>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <div class="jumbotron">
    <h1 class="display-4">Welcome to PATH</h1>
    <hr class="my-4">
    <p class="lead">PATH is a non-profit organization that provides temporary housing, food, and support services to homeless people. We believe that everyone deserves a safe place to live and the opportunity to rebuild their lives.</p>
  </div>

  <div class="row">
    <div class="col-md-4">
      <img src="{{ url_for('static', filename='Donated-Bikes1.jpg') }}" width="60%" height="60%">
    </div>
    <div class="col-md-4">
      <img src="{{ url_for('static', filename='FeedingHomeless4.jpg') }}" width="60%" height="60%">
    </div>
    <div class="col-md-4">
      <img src="{{ url_for('static', filename='PATH-Christmas2.jpg') }}" width="60%" height="60%">
    </div>
  </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}
					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-valid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
								{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-valid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-check">
					{{ form.remember(label='Remember Me') }}
				</div>
			</fieldset>
			<div>
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
			<small class="text-muted ml-2">
				<a href="#">Forgot Pasword?</a>
			</small>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Need An Account? <a class="ml-2" href="{{ url_for('auth.registerUser') }}">Sign Up Now</a>
		</small>
	</div>
{% endblock content %}

templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Join Today</legend>
				<dir class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-valid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
							<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control, form-control-lg") }}
					{% endif %}
				</dir>
				<dir class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-valid") }}
						<div>
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</dir>
				<dir class="form-group">
					{{ form.password.label(class="form-control-label") }}
						{% if form.password.errors %}
							{{ form.password(class="form-control form-control-lg is-valid") }}
							<div class="invalid-feedback">
								{% for error in form.password.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.password(class="form-control form-control-lg") }}
						{% endif %}
				</dir>
				<dir class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-valid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</dir>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Already Have An Account? <a class="ml-2" href="{{ url_for('auth.loginUser') }}">Sign In</a>
		</small>
	</div>
{% endblock content %}